import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const LINKS = [
  {
    name: "RHF1",
    href: "index1",
  },
  {
    name: "RHF2",
    href: "index2",
  },
  {
    name: "RHF3",
    href: "index3",
  },
  {
    name: "Image upload",
    href: "index4",
  }, {
    name: "controller",
    href: "index5",
  }
] as const;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {LINKS.map((link) => (
          <Link href={link.href} key={link.href}>
            {link.name} |{" "}
          </Link>
        ))}
      </main>
    </>
  );
}
